Repository fwupd/fwupd, pull requests merged in 2022-11, with the labels that each got.

#5229 Fix a regression when using fwuptool install-blob with FMAP firmware
  data/bash-completion/fwupdtool
  src/fu-tool.c
Labels: bug, regression

#5237 trivial: Do not show a critical warning without a request ID
  libfwupdplugin/fu-device.c
Labels: bug

#5178 Check system integrity when installing UEFI updates
  libfwupd/fwupd-enums.c
  libfwupd/fwupd-enums.h
  libfwupd/fwupd-self-test.c
  plugins/flashrom/fu-flashrom-plugin.c
  plugins/uefi-capsule/fu-uefi-capsule-plugin.c
  src/fu-engine-helper.c
  src/fu-engine-helper.h
  src/fu-engine.c
  src/fu-util-common.c
Labels: enhancement

#5239 fpc: Remove some dead code
  plugins/fpc/fu-fpc-device.c
Labels: bug

#5283 elantp: Include 04F3:0400 (bootloader) as a valid i2c-hid touchpad
  plugins/elantp/fu-elantp-hid-device.c
Labels: enhancement

#5285 intel-usb4: Ensure the device name is set with FuUsbDevice->setup
  plugins/intel-usb4/fu-intel-usb4-device.c
Labels: bug

#5286 Add more metadata to the report attributes
  contrib/codespell.cfg
  src/fu-engine.c
Labels: enhancement

#5288 Add FwupdReport to expose the signed reports from QA teams
  libfwupd/fwupd-enums-private.h
  libfwupd/fwupd-release.c
  libfwupd/fwupd-release.h
  libfwupd/fwupd-report-private.h
  libfwupd/fwupd-report.c
  libfwupd/fwupd-report.h
  libfwupd/fwupd-self-test.c
  libfwupd/fwupd.h
  libfwupd/fwupd.map
  libfwupd/meson.build
  src/fu-release.c
  src/fu-util-common.c
  src/fu-util-common.h
Labels: enhancement
