Repository fwupd/fwupd, pull requests merged in 2022-09, with the labels that each got.

#4995 Add shared functionality to get the parsed kernel cmdline
  libfwupdplugin/fu-kernel.c
  libfwupdplugin/fu-kernel.h
  libfwupdplugin/fwupdplugin.map
  src/fu-engine.c
Labels: enhancement

#5000 modem-manager: Fix a critical warning when issuing Secure Boot AT commands
  plugins/modem-manager/fu-mm-device.c
Labels: bug, regression

#4993 plugins: android-boot: new plugin
  contrib/fwupd.spec.in
  meson_options.txt
  plugins/android-boot/README.md
  plugins/android-boot/android-boot.quirk
  plugins/android-boot/fu-android-boot-device.c
  plugins/android-boot/fu-android-boot-device.h
  plugins/android-boot/fu-plugin-android-boot.c
  plugins/android-boot/meson.build
  plugins/meson.build
Labels: enhancement

#5004 Wip/hughsie/android boot
  plugins/android-boot/fu-android-boot-device.c
Labels: bug

#5013 trivial: Export fu_device_set_quirk_kv() for future use
  libfwupdplugin/fu-device-private.h
  libfwupdplugin/fu-device.c
  libfwupdplugin/fwupdplugin.map
Labels: enhancement

#5016 vbe: Fix a crash when dumping firmware
  plugins/vbe/fu-vbe-simple-device.c
Labels: bug

#5002 Add tests that emulate a USB device
  contrib/ci/oss-fuzz.py
  contrib/generate-ds20.py
  data/bash-completion/fwupdtool
  docs/ds20.md
  docs/fwupdplugin.toml.in
  docs/index.html
  libfwupdplugin/fu-backend-private.h
  libfwupdplugin/fu-backend.c
  libfwupdplugin/fu-backend.h
  libfwupdplugin/fu-context.c
  libfwupdplugin/fu-context.h
  libfwupdplugin/fu-usb-device-ds20.c
  libfwupdplugin/fu-usb-device-ds20.h
  libfwupdplugin/fu-usb-device-fw-ds20.c
  libfwupdplugin/fu-usb-device-fw-ds20.h
  libfwupdplugin/fu-usb-device-ms-ds20.c
  libfwupdplugin/fu-usb-device-ms-ds20.h
  libfwupdplugin/fu-usb-device.c
  libfwupdplugin/fwupdplugin.map
  libfwupdplugin/meson.build
  src/fu-engine.c
  src/fu-engine.h
  src/fu-self-test.c
  src/fu-tool.c
  src/fu-usb-backend.c
  src/tests/usb-devices-invalid.json
  src/tests/usb-devices.json
  subprojects/gusb.wrap
Labels: enhancement

#5055 trivial: Fix self tests when using -Dgresource_quirks=enabled
  libfwupdplugin/fu-quirks.c
Labels: bug

#5065 trivial: Install the devhelp symlinks relative
  docs/meson.build
Labels: bug
