Repository fwupd/fwupd, pull requests merged in 2023-07, with the labels that each got.

#5892 usi-dock: Adjust the display message according to the customer's requ…
  plugins/usi-dock/fu-usi-dock-mcu-device.c
Labels: needinfo

#5977 trivial: Fix self test failure on s390x
  libfwupdplugin/fu-efi-file-path-device-path.c
  libfwupdplugin/fu-efi-load-option.c
  libfwupdplugin/fu-self-test.c
  libfwupdplugin/fu-string.c
  libfwupdplugin/fu-string.h
  plugins/acpi-phat/fu-acpi-phat-health-record.c
  plugins/uefi-capsule/fu-uefi-capsule-plugin.c
  plugins/uefi-capsule/fu-uefi-cod-device.c
  plugins/uefi-capsule/fu-uefi-device.c
  plugins/uefi-capsule/fu-uefi-tool.c
Labels: bug

#5983 Add --no-security-fix to skip actions in 'fwupdmgr security'
  data/bash-completion/fwupdmgr
  data/fish-completion/fwupdmgr.fish
  src/fu-util.c
Labels: bug

#5991 Wip/hughsie/cfu modernization
  libfwupdplugin/fu-cfu-common.c
  libfwupdplugin/fu-cfu-common.h
  libfwupdplugin/fwupdplugin.h
  libfwupdplugin/meson.build
  plugins/cfu/fu-cfu-device.c
  plugins/cfu/fu-cfu-module.c
  plugins/cfu/fu-cfu.rs
  plugins/cfu/meson.build
  plugins/elanfp/fu-elanfp-device.c
  plugins/elanfp/meson.build
Labels: bug, enhancement

#6028 uefi-capsule: Do not assume the logical block size is always 0x200
  libfwupdplugin/fu-efi-hard-drive-device-path.c
  libfwupdplugin/fu-volume.c
  libfwupdplugin/fu-volume.h
  meson.build
Labels: regression

#6039 Set some feature flags when non-interactive
  src/fu-util.c
Labels: bug
