Repository fwupd/fwupd, pull requests merged in 2024-01, with the labels that each got.

#6588 bugfix: remove unused device
  plugins/dell/dell.quirk
Labels: needs-backport

#6573 New plugin, Algoltek-USB, is added for updating Algoltek ASIC firmware
  plugins/algoltek-usb/README.md
  plugins/algoltek-usb/algoltek-usb.quirk
  plugins/algoltek-usb/fu-algoltek-usb-common.h
  plugins/algoltek-usb/fu-algoltek-usb-device.c
  plugins/algoltek-usb/fu-algoltek-usb-device.h
  plugins/algoltek-usb/fu-algoltek-usb-firmware.c
  plugins/algoltek-usb/fu-algoltek-usb-firmware.h
  plugins/algoltek-usb/fu-algoltek-usb-plugin.c
  plugins/algoltek-usb/fu-algoltek-usb-plugin.h
  plugins/algoltek-usb/fu-algoltek-usb.rs
  plugins/algoltek-usb/meson.build
  plugins/meson.build
Labels: needs-backport

#6569 trivial: set fingerprint reader in Framework laptops as will-disappear
  plugins/goodix-moc/fu-goodixmoc-device.c
  plugins/goodix-moc/goodixmoc.quirk
Labels: needs-backport

#6622 trivial: Make an error string more useful
  src/fu-engine.c
Labels: needs-backport

#6629 Fix an assertion when enabling lvfs-testing for the first time
  libfwupd/fwupd-client.c
Labels: bug, needs-backport

#6641 Avoid crashing the daemon if not using udisks to check for size
  libfwupdplugin/fu-volume.c
Labels: bug, needs-backport

#6645 cpu: Show "CET OS support" on AMD systems too
  plugins/cpu/fu-cpu-device.c
Labels: needs-backport

#6650 snap: Enable access to the home interface
  contrib/snap/snapcraft.yaml
Labels: needs-backport

#6664 trivial: Fix lockdown message
  src/fu-util.c
Labels: needs-backport

#6670 trivial: man: strip leading whitespace too
  generate-build/generate-man.py
Labels: needs-backport

#6665 Wip/hughsie/idle device changed allowlist
  src/fu-engine.c
  src/fu-idle.c
  src/fu-idle.h
  src/fu-self-test.c
Labels: needs-backport

#6675 Wip/hughsie/esp recovery
  plugins/uefi-capsule/fu-uefi-capsule-plugin.c
Labels: needs-backport

#6697 trivial: don't show `HSI attribute %s (from %s) had unknown result` t…
  src/fu-engine.c
Labels: needs-backport

#6702 trivial: Include the fwupd.conf IdleTimeout default in the man page
  docs/fwupd.conf.md
  src/fu-engine-config.c
Labels: needs-backport

#6711 trivial: add FWUPD_REQUEST_FLAG_ALLOW_GENERIC_MESSAGE to uefi-capsule…
  plugins/uefi-capsule/fu-uefi-capsule-plugin.c
Labels: bug, needs-backport

#6698 trivial: drop systemd unit detection
  src/fu-systemd.c
  src/fu-systemd.h
  src/fu-tool.c
  src/fu-util-common.c
  src/fu-util-common.h
  src/fu-util.c
Labels: needs-backport

#6735 Wip/hughsie/config comments main
  libfwupdplugin/fu-config.c
Labels: needs-backport

#6736 Use the history-provided verfmt in more cases
  src/fu-engine.c
  src/fu-self-test.c
Labels: bug, needs-backport

#6739 Store the version format in the history database
  libfwupdplugin/fu-device.c
  libfwupdplugin/fu-dpaux-device.c
  plugins/uefi-capsule/fu-uefi-device.c
  src/fu-engine.c
  src/fu-history.c
  src/fu-self-test.c
Labels: bug

#6741 debian/tests/ci: Put all stderr into stdout. fwupdtool is pretty verbose with messages that happen to go to stderr but aren't errors.
  contrib/debian/tests/ci
Labels: needs-backport

#6738 trivial: Fix a critical warning when validating broken FuGenesysUsbhu…
  plugins/genesys/fu-genesys-common.h
  plugins/genesys/fu-genesys-usbhub-device.c
  plugins/genesys/fu-genesys-usbhub-firmware.c
  plugins/genesys/fu-genesys-usbhub.rs
Labels: bug
