Repository fwupd/fwupd, pull requests merged in 2024-05, with the labels that each got.

#7179 Add a new plugin to update Algoltek DisplayPort devices
  plugins/algoltek-aux/README.md
  plugins/algoltek-aux/algoltek-aux.quirk
  plugins/algoltek-aux/fu-algoltek-aux-device.c
  plugins/algoltek-aux/fu-algoltek-aux-device.h
  plugins/algoltek-aux/fu-algoltek-aux-firmware.c
  plugins/algoltek-aux/fu-algoltek-aux-firmware.h
  plugins/algoltek-aux/fu-algoltek-aux-plugin.c
  plugins/algoltek-aux/fu-algoltek-aux-plugin.h
  plugins/algoltek-aux/fu-algoltek-aux.rs
  plugins/algoltek-aux/meson.build
  plugins/meson.build
Labels: enhancement

#7215 Add if running in CI to the useragent
  libfwupd/fwupd-client.c
Labels: enhancement

#7221 Do not verify the SSL hostname when using DISABLE_SSL_STRICT=1
  libfwupd/fwupd-client.c
Labels: bug

#7224 trivial: only build cet helper on x86-64
  plugins/cpu/meson.build
Labels: needs-backport

#7223 x86-64: Trigger shadow stack violation in assembly
  plugins/cpu/fu-cpu-helper-cet-common.S
  plugins/cpu/fu-cpu-helper-cet-common.c
  plugins/cpu/meson.build
Labels: needs-backport

#7268 Invalidate the original input stream if using fu_firmware_set_bytes()
  libfwupdplugin/fu-firmware.c
Labels: bug, regression

#7282 trivial: catch miscategorized ESP partitions
  plugins/uefi-capsule/fu-uefi-capsule-plugin.c
Labels: needs-backport
