Repository fwupd/fwupd, pull requests merged in 2024-04, with the labels that each got.

#7032 Use zst as the file extension for zstd
  meson.build
  src/fu-remote-list.c
  src/fu-self-test.c
Labels: needs-backport

#7038 Use the specific release when fixing up device history
  src/fu-engine.c
Labels: bug

#7039 Drop heap as part of a housekeeping action
  src/fu-daemon.c
  src/fu-main.c
Labels: enhancement

#7053 trivial: make udisks partition proxy optional
  libfwupdplugin/fu-volume.c
  libfwupdplugin/fu-volume.h
Labels: needs-backport

#7061 trivial: snap: build with newer libxmlb
  contrib/snap/snapcraft.yaml
Labels: needs-backport

#7071 Limit the size of the allocations in libcbor
  contrib/ci/oss-fuzz.py
  libfwupdplugin/fu-coswid-firmware.c
  meson.build
Labels: bug

#7073 trivial: Fix a several possible memory leaks for an invalid coswid file
  libfwupdplugin/fu-coswid-firmware.c
Labels: bug

#7031 Set a generic message request flag when the ID is known
  src/fu-engine.c
Labels: bug, needs-backport

#7116 optionrom: Do not read OptionROM on Apple hardware
  plugins/optionrom/fu-optionrom-plugin.c
  plugins/optionrom/meson.build
  plugins/optionrom/optionrom.quirk
Labels: needs-backport

#7104 Hughsie/cbor uint8
  libfwupdplugin/fu-coswid-firmware.c
Labels: bug, needs-backport

#7132 Hughsie/ccgx dmc downgrade
  plugins/ccgx-dmc/fu-ccgx-dmc-device.c
  plugins/ccgx-dmc/fu-ccgx-dmc.rs
Labels: bug

#7140 trivial: Fix a crash when parsing invalid COSWID files
  libfwupdplugin/fu-coswid-firmware.c
Labels: needs-backport

#7139 trivial: Do not rely on @memlock not being part of @system-service
  data/meson.build
Labels: needs-backport

#7146 trivial: Fix the MISR calculation
  libfwupdplugin/fu-crc.c
  libfwupdplugin/fu-self-test.c
Labels: needs-backport

#7171 Hughsie/more syscalls
  data/fwupd.service.in
  data/meson.build
Labels: bug, needs-backport

#7167 Fix a logic thinko when parsing GUID strings
  libfwupd/fwupd-common.c
Labels: bug, needs-backport

#7163 pci-mei: Assume new ME versions are called CSME
  plugins/pci-mei/fu-pci-mei-plugin.c
Labels: bug, needs-backport
