Repository fwupd/fwupd, pull requests merged in 2025-01, with the labels that each got.

#8323 Fix an issue where UEFI capsule reboot_cleanup wasn't running
  plugins/uefi-capsule/fu-uefi-capsule-plugin.c
Labels: needs-backport

#8334 amd-gpu: Split up the VBIOS P/N for the version
  plugins/amd-gpu/fu-amd-gpu-device.c
  plugins/amd-gpu/tests/amd-apu.json
  plugins/amd-gpu/tests/amd-dgpu-navi3x.json
  plugins/amd-gpu/tests/amd-dgpu.json
Labels: needs-backport

#8371 Allow skipping device tests by CPU architecture
  src/fu-util.c
Labels: enhancement

#8407 trivial: Compile as ISO/IEC 9899:2018
  meson.build
Labels: enhancement

#8416 Do not close the base stream when decompressing uSWID firmware
  libfwupdplugin/fu-uswid-firmware.c
Labels: bug

#8419 Fix dbx deployment by ignoring missing PE/COFF sections
  libfwupdplugin/fu-pefile-firmware.c
Labels: bug
